# Generated by Django 3.0.8 on 2020-07-16 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='facebook',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='instagram',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
