# Generated by Django 3.0.8 on 2020-07-19 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200716_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Freelancer'),
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(choices=[(1, 'BAD'), (2, 'MEDIUM'), (3, 'GOOD'), (4, 'AWESOME')])),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Freelancer')),
            ],
        ),
    ]
